services:
  # REDIS RUNS IN DOCKER
  redis:
    image: redis:7-alpine
    container_name: foodies_redis
    restart: always
    ports:
      # Exposes Docker's internal Redis port 6379 to my local 127.0.0.1:6379
      - "6379:6379"
    volumes:
      - redis_data:/data

volumes:
  redis_data: